docs/ch05-network-interfaces.rst, docs/ch06-routing.rst
line 161 was a sphinx complaint, not sure if you have seen the warning I used sphinx 1.4.9.
Let me know if you want something changed, I see that I copy from the wiki more into here, I have the syslog documentation to do as well. Especially with having crux released soon.
=> Adding wireguard documentation to ch05.

docs/ch12-system.rst
=> T759: Update wiki.vyos.net syslog config options

docs/quick-start.rst, docs/services.rst
in 1.2.0-rc11 you must use range
=> dhcp ranges

docs/network-interfaces.rst
it's at least a start of how to use wireless
=> added wireless interface example

.gitignore
Makes it easier to use python virtualenv for sphinx as well as reducing the risk of getting various editor files in there.
=> a gitignore would make life better

docs/qos.rst
Add a general real-world (home-use perhaps) example of QoS with traffic prioritization by matched class.
=> Update qos.rst; add general example

docs/troubleshooting.rst
fix reference error to cli section in troubleshooting
=> fix reference to cli

docs/cli.rst, docs/commandtree/configmode.rst, docs/commandtree/index.rst, docs/commandtree/operationmode.rst, docs/index.rst
add Config Tree as "Appendix C" and first Operational mode entries
=> add Config Tree and op mode

docs/interfaces/dummy.rst, docs/interfaces/index.rst
still needs improvements but now it's there.
=> add dummy interfaces

README.md
=> Fix missing letters

docs/contributing/index.rst, docs/index.rst
take much from the wiki and some pages of https://blog.vyos.io/tag/vyconf
=> add VyOS contribution guide

docs/troubleshooting.rst
add monitor bandwith and bandwith-test
=> improve monitor command

docs/interfaces/addresses.rst, docs/interfaces/index.rst
=> fix interface toctree

docs/examples/dmvpn.rst, docs/examples/index.rst, docs/examples/zone-policy.rst, docs/firewall.rst, docs/index.rst
And prepare for more examples by adding them to their own subdirectory
=> Add the zone-example from wiki

docs/appendix/examples/bgp-ipv6-unnumbered.rst, docs/appendix/examples/index.rst
Add example  for BGP IPv6 unnumbered with extended nexthop and ecmp
=> Add BGP IPv6 unnumbered example

docs/appendix/examples/index.rst, docs/appendix/examples/ospf-unnumbered.rxt
Example configuration for ospf ip unnumbered
=> Add ospf unnumered

docs/services/pppoe-server.rst
=> Add RADIUS DM/CoA: update pppoe-server.rst

docs/services/pppoe-server.rst
=>  Small typo fix: update pppoe-server.rst

docs/index.rst, docs/load-balancing.rst
Add WAN load balancing section.
=> add wan load-balancing

docs/vpn/dmvpn.rst, docs/vpn/l2tp_ipsec.rst
get links back working after they gone due split of vpn section
=> get links back working

docs/appendix/migrate-from-vyatta.rst, docs/configuration-overview.rst, docs/history.rst, docs/index.rst, docs/install.rst, docs/vpn/gre-ipsec.rst, docs/vpn/index.rst
This is the first of many PR's to get data over from the wiki to readthedocs
=> T145: Migrate vyos history, migrate vyatta, ipsec-gre and restructure of configuration overview

docs/vpn/openvpn.rst
=> Fix smal typo

docs/appendix/examples/dmvpn.rst
=> missing a command in the Cisco IPsec Profile

docs/cli.rst, docs/configuration-overview.rst, docs/install.rst
Fix typos
Add and clarify explanations
Add terminology from wiki
=> Edit conf overview

docs/install.rst
Reorder steps. Verifying signatures is now before installing.
Delete `gpg --import maintainers.key`
and add `gpg --recv-keys FD220285A0FE6D7E ` instead.
Add some explanations.
=> improve install doc and try my first commit :)

docs/cli.rst, docs/install.rst
- Add a link to the command tree page of the appendix.
- Explain normal scrolling.
=> Edit cli doc

docs/configuration-overview.rst
Explain what the "greater than" sign means when displaying configuration.
Provide an example.
=> explain and provide example of > sign

docs/install.rst
Reorder subsections and clarify how to get PGP signatures.
=> clarify how to get image signatures

docs/appendix/examples/azure-vpn-bgp.rst, docs/appendix/examples/azure-vpn-dual-bgp.rst
Had a quick chat with @dmbaturin on Slack regarding the validation of Vyos for Microsoft Azure, i.e. getting Microsoft to validate it and add it to this list: https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpn-devices#devicetable
This is related to that conversation.
One of the requirements is to have public documentation that shows users how to configure a tunnel between the device and Azure native VPN, this is a contribution to start that work. Please take a look and let me know any changes, improvements, etc
@dmbaturin also mentioned an interest on hearing more about how can we get the "configuration download" feature on Azure portal to also generate Vyos configs. I will be reaching out to Microsoft for more information on that. 
**Disclaimer**: I worked at …
=> Added Azure VPN examples

docs/load-balancing.rst
Fixed some typos and also made some lines more consistent with each other
=> Fix typos in load-balancing.rst

docs/firewall.rst, docs/vpn/openvpn.rst
Adding a note on `openvpn-option -reneg-sec`
=> Openvpn reneg

docs/firewall.rst
Describe command `firewall all-ping`
=> firewall_all-ping

docs/routing/pbr.rst
Example rule 20 was used twice
=> Example was broken

docs/interfaces/ethernet.rst, docs/interfaces/pppoe.rst, docs/interfaces/tunnel.rst, docs/routing/static.rst
ethernet.rst: Exploded out some example text into a list
pppoe.rst: Rewrote a few paragraphs, including one of the longest sentences I have ever seen
tunnel.rst: Slight rewrite, spelling problem
static.rst: Slight rewrite and corrected a spelling problem.
=> Spelling, a few minor rewrites.

docs/configuration-overview.rst
Add how to wipe configuration and restore the default one
=> wipe config

docs/system/index.rst, docs/system/ntp.rst
=> add system NTP section

docs/appendix/vyos-on-vmware.rst, docs/index.rst
Added paragraph on issues with vyos on vmware in memory contending environments,
=> Added vyos on vmware page and rudimentary structure.

docs/interfaces/bridging.rst
=> Fixed Example

docs/configuration-overview.rst
There was a lot of duplication surrounding configuration archiving.  This was cleaned up and combined into the appropriate section
=> Significant cleanup and deduplication

docs/history.rst
I rewrote a few things and cleaned up some grammar and punctuation.  Added more information regarding current capabilities.
=> Significant rewrite

docs/install.rst
Add link to latest Rolling release and add instructions for installation through PXE.
=> latest release link and PXE

docs/load-balancing.rst
https://phabricator.vyos.net/T1560
=> Delete faulty rule 0 in example

docs/vpn/wireguard.rst
show interfaces wireguard X example updated to reflect new output
=> wireguard:  Update example run show output

docs/interfaces/bridging.rst
The bridging example mixed old styling bridging with new style
=> [Bridging]: Fixing bad example

docs/appendix/vyos-on-vmware.rst, docs/index.rst, docs/vpn/dmvpn.rst
Not sure why it is wanting to add my work on VyOS on VMWARE again, I dont play with git enough obviously.
Adding notes on DMVPN, and DMVPN in AWS.
=> Added DMVPN notes

docs/contributing/build-vyos.rst
Spelling and grammar clean up.  Removing some conversational language.
=> contribution: build cleanup

docs/Makefile, docs/appendix/examples/ha.rst, docs/appendix/examples/index.rst
This is reasonably brief but touches on all the important things to do when setting up a HA VyOS cluster. It could probably do with some massaging and double checking, as I wrote it pretty much all from memory.
=> Add first stab of walkthrough of HA

docs/conf.py, docs/contributing/documentation.rst, docs/interfaces/geneve.rst, docs/interfaces/wireless.rst, docs/routing/arp.rst, docs/vpn/openvpn.rst
Change cfmd to cfgcmd for a better typing feeling.
=> cfgcmd for better typing feeling

docs/routing/bgp.rst
Add protocol "RPKI" in section ./routing/bgp.rst
=> bgp: add section RPKI

docs/configuration-overview.rst, docs/vpn/openvpn.rst
restore commit 20a28ff77946f0c9ff081ed8a37c645a01082c06 about configuration wipe out
=> Restore commit 20a28ff

docs/contributing/build-vyos.rst
This is copied from the vyos-build README.md with some changes and updates.
=> contribution: build: add section about building packages

docs/system/flow-accounting.rst
- added information about sFlow
- replaced op-mode examples by modern ones
=> Extended flow-accounting documentation

docs/conf.py
=> Sphinx: integrate standalone vytask in conf.py

docs/contributing/documentation.rst
Fix typos in contribution guideline
=> Fix contribution guideline typos

README.md
Fix native build layout and revise the steps to use python3 which is  required for using sphinx and building the html targets
=> Revise native build

docs/routing/rpki.rst
In this PR I have:
* amended to use the RFC5737 documentation prefix
* fixed some spelling and grammar
* added more detail to explain how to get started running an RPKI validating server
=> more detail about RPKI

docs/routing/rpki.rst
Implement https://twitter.com/alexander_band/status/1231542836996255744
=> add links to further RPKI guidance

docs/appendix/http-api.rst, docs/index.rst
Operational requests and configuration management requests.
Ad discussed with @dmbaturin, for the time being we are not including image management requests or show config requests.
=> appendix: http-api

docs/services/conntrack.rst
separate active router and standby router
=> conntrack: split last code-block

docs/nat.rst
Convert a note into subsection and adjust texts to 72 columns.
=> nat: edit format and indentation

docs/vpn/l2tp.rst
Add explanation on UDP-encapsulating ESP for NAT
and add another example of possible DNS server.
=> l2tp: adding small details

docs/quick-start.rst
https://phabricator.vyos.net/T2209
=> T2209: Remove old user level from quick start

docs/services/dynamic-dns.rst
Updating docs as a follow up from this forum post:
https://forum.vyos.io/t/dynamic-dns-with-namecheap/5015/5
=> Clarify login field when using Namecheap

docs/contributing/development.rst
Not sure how the text will render.
=> debug: document the various flags

docs/appendix/http-api.rst
how to run opsmode  commands /generate and /show
https://phabricator.vyos.net/T2096
=> documented T2096  how to run opsmode 

docs/services/router-advert.rst
=> Changing "psuedo-ethernet" to "pseudo-ethernet"

docs/contributing/build-vyos.rst
Put some more detail into the building instructions on how to build.
=> T2474: Contributing/Docker: Put more detail into building instructions.

docs/contributing/build-vyos.rst
correct docker container name(from vyos/vyos-builder to vyos/vyos-build)
=> correct docker container name(from vyos/vyos-builder to vyos/vyos-build)

docs/firewall.rst, docs/services/dns-forwarding.rst
Various typo fixes and edits for clarity.
=> Update DNS Forwarder and Firewall Pages

docs/contributing/build-vyos.rst
Port over changes merged in #284. Instructions for building packages from source also added.
=> build-vyos: Port over changes merged in #284

docs/contributing/build-vyos.rst
i think, let me know if this is the proper way to improve documentation.
these are just some things I noticed that I thought was wrong while building the iso myself.
if i was correct in this, there is the same problem in the crux branch of documentation
=> changed small errors in build-vyos.rst

docs/qos.rst
Pleae revert Pull Request from @hlmtre
The typo correction is fine, the rest is wrong.
=> Revert "Correct small typos; add matching examples"

docs/vpn/openvpn.rst
The topic "Generate X.509 Certificate and Keys" is added in the OpenVPN chapter to explian the steps to generate the server/client cert and key files for the latest version.
=> "Generate X.509 Certificate and Keys" is added in the OpenVPN

docs/appendix/vyos-on-clouds.rst
=> Azure: Add new interface

docs/qos.rst
Backport my last 4 commits on QoS
=> Backport last 4 QoS commits to Crux

docs/troubleshooting.rst
Some syntax and use case description errors were found, so fix them here
=> ipv6-tool: T2724: Modify the use case and syntax description of router  discovery

docs/system/advanced-index.rst, docs/system/system-display.rst
This is the documentation for Task [T2564](https://phabricator.vyos.net/T2564)
Thanks for considering it for inclusion into a future release.
=> System display: T2564 Extend VyOS to support appliance LCDs

docs/contributing/build-vyos.rst
I think that is a good way to contribute to this beautiful project :)
=> fix bad typing

docs/contributing/build-vyos.rst
The docker run command was missing of the correct container label.
=> Docker run command

docs/install.rst
Add the creation of a bootable USB drive and other improvements.
=> installation: backport recent additions

docs/about.rst
I've fixed some typos in the about page of the docs.
=> Fix typo about

docs/configuration-overview.rst
Add commands: commit-confirm, copy, rename, show system commit diff <number>.
Add few little clarifications too.
=> configuration overview: add missing contents from old wiki.

docs/nptv6.rst
=> nptv6: replace outside-interface command with outbound-interface command

docs/install.rst
https://support.sentrium.io/agent/go/ticket/1268
=> install: pxe: warn about keeping filesytem.squashfs name

docs/routing/mpls.rst
Due to the added amount of functionality in the MPLS parts of VyOS, I wanted to add more clarity and update the documentation.
=> * :vytask:`T2989` MPLS documentation expansion

docs/contributing/build-vyos.rst
'harder' doesn't make sense. The intention must have been to say 'hardware'.
I realize that there is a big process to contributing to this project (https://docs.vyos.io/en/latest/contributing/documentation.html), I can _make_ and _build_ it locally if I really start contributing more documentation, but this is super simple.
I am just getting started with vyos and am glad to see so much documentation. I look forward to contributing!
=> Minor typo correction

docs/contributing/documentation.rst
changes include:
- a consistent reference to the branch name
- installing requirements before building locally
- an alternate method for adding a commit message
=> Forking Workflow: revisions to the forking workflow instructions

docs/about.rst, docs/index.rst
Add toctree captions and names to separate blocks
(similar to 1.3 index) without affecting existing links
=> index: establish highlighted blocks without affecting links

docs/interfaces/wireless.rst
You need to supply a channel number at the end.
=> fix syntax for vht center-channel-freq

docs/configuration/protocols/mpls.rst
Added examples for the new import and export functionality that
LDP is now getting on vyos/vyos-1x#639
=> mpls-conf: T915: Added documentation for LDP import and export

docs/configuration/system/flow-accounting.rst
I think i've done a error with the ordering. Sorry for that :/
=> flow-accounting: T3132: Fixing ordering

docs/configuration/vpn/ipsec.rst, docs/configuration/vpn/rsa-keys.rst
RSA-Keys page was blank, so added the steps to generate and add the keys to
the VPN IPSec config.
Also corrected the IPSec/GRE page where authentication parameter was
missing before remote-id.
=> RSA Keys: Added information related to RSA keys

docs/configuration/zonepolicy/index.rst
zone-policy page was blank, added the definition and the configuration
example.
=> zone-policy: page information is added

docs/installation/cloud/azure.rst
Started reading through the Azure deployment docs to update our process to not have to upload a vhd each time we create a vyos VM. Found some things we do that might be useful to have in the docs.
=> Azure docs update

docs/configuration/protocols/bgp.rst
The document now meets the maximum line length requirements
Add route reflector commands
Add soft-reconfiguration
Add default originate
=> bgp: add configuration commands and their explanatios

docs/configuration/protocols/bgp.rst
Placed upper more often used commands;
Add route filtering;
Add confederation commands;
Add route dampening.
=> bgp: change comand order, add route filterig

docs/configuration/protocols/ospf.rst
Added OSPFv3 configuration and operation commands.
OSPFv2 formatted according to Style Guide.
added summarization commands for OSPFv2.
=> OSPF: added OSPFv3 commands and formated OSPFv2

docs/configuration/interfaces/pppoe.rst
Fleshed out PPPoE interface documentation to reflect behaviour change implemented in https://github.com/vyos/vyos-1x/pull/711.
=> pppoe: T3273: Add usage of each default-route mode

docs/_ext/testcoverage.py
Task T2910 added support for overriding <defaultValue> elements in the XML interface definitions by adding a subsequent entry with a different value; it is left to a pre-processing script to collect redundant elements at the same path and replace with the final instance. Since the vyos-documentation testcoverage.py script validates this XML against the schema, the same pre-processing need to be called.
=> process overriding of defaultValue elements in XML interface definitions

docs/configuration/highavailability/index.rst
Added a reference link of scripting page in the vrrp.
=> Added a reference link of scripting page in the vrrp.

docs/_include/interface-dhcp-options.txt
Add DHCP default route distance.
https://phabricator.vyos.net/T3300
https://github.com/vyos/vyos-1x/pull/729
=> dhcp: T3300: add DHCP default route distance

docs/automation/index.rst, docs/automation/vyos-ansible.rst
Example of how to use ansible for vyos configuration.
=> Add ansible to doc

docs/configuration/protocols/isis.rst
The previous tagNode was replaced with a regular node.
This must be merged together with https://github.com/vyos/vyos-1x/pull/779
=> isis: adjust to latest CLI changes

docs/configuration/protocols/ospf.rst
Modified the commands as per the latest rolling release.
=> Correction of the syntax for "Interface Configuration" OSPFv3 section

docs/configexamples/ha.rst
Corrected the syntax for wireguard interface commands wrt ospf
=> syntax correction in OSPF Over wireguard section

docs/_include/interface-dhcpv6-prefix-delegation.txt
Find a minor typo and would like to merge in a correction.  This is my first time merging into this repository; please provide feedback or correction as necessary.
=> Fixed interfcae to interface in dhcpv6 page

docs/documentation.rst
fixes some grammar errors and improve the flow of some sentences
=> Grammar and style changes to documentation guide

docs/_include/interface-dhcp-options.txt
Documentation changes needed for vyos/vyos-1x#799
=> interfaces: dhcp-client: T3454: add reject option

docs/configexamples/dhcp-relay-through-gre-bridge.rst, docs/configuration/interfaces/tunnel.rst
added the command configuration for gretap and corrected the syntax in dhcp-relay
example page
=> T3458:tunnel interface:added GRETAP section

docs/configuration/interfaces/tunnel.rst
Bymistakenly wrote gretap for 1.3 version, corrected with "GRE-Bridge" parameter
=> T3458-e:1.3 ver:tunnel interface:replaced GRETAP with GRE-Bridge

docs/contributing/build-vyos.rst
- Update documents to build
https://phabricator.vyos.net/T3485
https://github.com/vyos/vyos-utils-misc/pull/1
=> Update build to include MacOS support

docs/configexamples/ha.rst, docs/configuration/highavailability/index.rst
Added the details of rfc3768-compatibility option and its command
=> VRRP: addition  of rfc3768-compatibility definition

docs/configexamples/ha.rst, docs/configuration/highavailability/index.rst
Added the details of rfc3768-compatibility option and its command
=> VRRP(equuleus): addition  of rfc3768-compatibility definition

docs/configuration/highavailability/index.rst
Added the details of rfc3768-compatibility option and its command
=> VRRP(crux): addition  of rfc3768-compatibility definition

docs/configuration/service/dns.rst
Added documentation on new feature
=> dns: T3277: DNS Forwarding - no serve rfc1918 add documentaton

docs/configuration/service/tftp-server.rst
Added  verification section so that it will in testing the feature
=> TFTP: verification help

docs/contributing/build-vyos.rst
Updated build step in order to correctly point to _current_ branch.
=> Fix documentation instructions

docs/configexamples/tunnelbroker-ipv6.rst
This is using the changes from vyos/vyos-1x@857294427afba3259e683f2360c735f0f4be32b6 and vyos/vyos-1x@582b718221c67ddb71e39fbad0a72241761304a9
=> Updated tunelbroker example to use updated config paths

docs/configuration/service/tftp-server.rst, docs/configuration/system/syslog.rst
Added a help section for the "delete log file" command
=> system:syslog: added delete log file section

docs/automation/command-scripting.rst
I add a description about custom scripts that run after/before commit
=> automation: add custom pre/post-commit hooks

docs/automation/command-scripting.rst
I add information about preconfig scripts
=> Automation doc scripts

docs/configuration/container/index.rst, docs/configuration/index.rst
Added the currently available configuration commands for the new Podman addition to Vyos. Code was built and tested successfully. 
By no means am I a technical writer, so this documentation could use some editing for clarification.
=> Add configuration command references for containers

docs/configuration/service/dhcp-server.rst
Add support for dhcpdv6 fixed-prefix6.
https://phabricator.vyos.net/T3658
https://github.com/vyos/vyos-1x/pull/902
=> dhcpdv6: T3658: add support for dhcpdv6 fixed-prefix6

docs/configuration/vrf/index.rst, docs/operation/information.rst
spelling and grammatical check
=> vrf page: multiple typos and grammatical mistakes

docs/configuration/policy/index.rst, docs/configuration/protocols/static.rst
correction of configuration error
=> correction of configuration error

docs/automation/cloud-init.rst
Fixed syntax issues with the config file example and added little more information.
=> cloud-init: fixes and additions

docs/configuration/vpn/dmvpn.rst, docs/configuration/vpn/l2tp.rst, docs/configuration/vpn/pptp.rst
correction of typo and grammatical mistakes
=> Vpn pptp/l2tp

docs/configuration/interfaces/bridge.rst
add some correction with respect to show operation command
=> bridge: correct oper commands

docs/installation/cloud/aws.rst, docs/installation/cloud/azure.rst, docs/installation/cloud/cloud-init.rst, docs/installation/cloud/gcp.rst, docs/installation/image.rst, docs/installation/vyos-on-baremetal.rst
=> grammar correction

docs/cli.rst, docs/commandtree/configmode.rst, docs/commandtree/operationmode.rst, docs/quick-start.rst
=> proof-reading

docs/automation/cloud-init.rst
This PR enhances the cloud-init documentation by adding a section on executing linux and VyOS operational commands at the time of initial boot.
I want to give credit to Taras Pudiak. I appreciate his guidance on cloud-init.
=> Add command execution at initial boot section to cloud-init

docs/configuration/service/snmp.rst
=> Corrected Typo

docs/installation/virtual/proxmox.rst
The changes in this PR instruct the reader how to import the qcow2 image into proxmox and create a virtual machine.
=> Enhance proxmox installation instructions

docs/configuration/vrf/index.rst
the idea is add documentation for this new Feature L3vpn vrf
=> doc: L3vpn: settings

docs/configuration/interfaces/openvpn.rst
Removed unnecessary crypt-key command, corrected tls configuration for LDAP and added a note to commit each PKI information before applying under the OpenVPN interface.
=> Minor changes and corrections

docs/configuration/vrf/index.rst
the idea is create a basic example where we can see the configuration .
=> doc: L3vpn: configuration basic

docs/cli.rst
Add description for op-mode command `show configuration json`
=> op-mode: Add doc for show configuration JSON

docs/cli.rst
Add description for op-mode command `show configuration json` for 1.4
=> op-mode: Add doc for show configuration JSON 1.4

docs/configuration/vpn/ipsec.rst
ESP group parameters for IPsec
=> ESP group parameters

docs/installation/virtual/docker.rst, docs/installation/virtual/index.rst
Add instructions for installing vyos in a docker container from ISO
=> Add docker installation guide

docs/operation/index.rst, docs/operation/raid.rst
I add the step by step how to create a raid-1 on VyOS , it should be useful  for all version.
=> Raid-1 add documentation

docs/_templates/layout.html
Per https://blog.vyos.io/vyos-1.3.0-lts-release
=> Updating stable release banner

docs/contributing/build-vyos.rst
- Added Ubuntu, Fedora, and Centos
- Removed '$' for copy/paste-ability
- Added links to relevant install pages
=> Improved docker install instructions

docs/configuration/highavailability/index.rst
Add missing options for VRRP, add  examples for virtual-server
=> ha: Documentation for VRRP and virtual-server

docs/configuration/service/index.rst, docs/configuration/service/monitoring.rst
Add `set service monitoring telegraf` doc.
=> Add service monitroting telegraf

docs/configuration/service/snmp.rst
Fixed sentence and spelling mistakes
=> proof-reading: snmp : correction of typo

docs/configuration/policy/local-route.rst
https://github.com/vyos/vyos-1x/pull/1196
https://github.com/vyos/vyos-1x/pull/1144
=> policy: T4151: T4219: update local-route(6) docs

docs/automation/cloud-init.rst
Updated automtion/cloud-init file, and now bulleted lists looks OK.
=> Automation/Cloud-init - bulleted list corrections

docs/automation/cloud-init.rst
Instructions for using cloud-init in Proxmox environment.
=> Automation/Cloud-init - How-to cloud-init  in Proxmox

docs/configuration/vpn/openconnect.rst
Updated syntax to match 1.4.x.
=> Updated OpenConnect SSL Syntax

docs/configuration/policy/route-map.rst
Documentation changes to go along with https://github.com/vyos/vyos-1x/pull/1243
=> policy: T2493 ip-next-hop unchanged & peer-address

docs/configuration/protocols/ospf.rst
add Documentation changes to go along with https://github.com/vyos/vyos-1x/pull/1250
=> ospf: add export-list/import-list & mamixum-paths

docs/configuration/service/dhcp-server.rst
Signed-off-by: Georg Pfuetzenreuter <mail@georg-pfuetzenreuter.net>
Supplements https://github.com/vyos/vyos-1x/pull/1148.
=> dhcp-server: T4156: Add bootfile-size option

README.md
I think this is what is known as an open compound
=> minor documentation change

docs/changelog/1.3.rst, docs/configuration/firewall/index.rst
Remove note that stands that firewall groups are usable in nat
=> Remove note on firewall

docs/automation/cloud-init.rst
=> add link to write_files format documentation

docs/automation/vyos-api.rst, docs/configuration/service/https.rst
Add API action `reset`
Add option `api socket`
=> http-api: Add action reset and socket description

docs/configuration/service/ssh.rst
Add `set service ssh dynamic-protection`
=> sshguard: Add ssh dynamic-protection

docs/configuration/firewall/index.rst
- Add documentation for rule log-level.
- PR when that feature was added: https://github.com/vyos/vyos-1x/pull/1322
- Add documentation for possibility of using negated groups on firewall.
- Add documentation for ttl and hop-limit matching criteria:
- PR recently merged for ttl: https://github.com/vyos/vyos-1x/pull/1355
=> Firewall: Add firewall documentation

docs/configuration/firewall/index.rst
Add geoip matching criteria documentation
Phabricator task: https://phabricator.vyos.net/T4299
=> Firewall: T4299: add geoip matching criteria

docs/configuration/service/conntrack-sync.rst
Changed commands syntax to new new format
=> conntrack-sync: Changed commands syntax

docs/_include/interface-ip.txt, docs/configuration/system/ip.rst
Feature PR https://github.com/vyos/vyos-1x/pull/1402 has been merged.
=> Add directed broadcast forwarding documentation

docs/configuration/service/router-advert.rst
for PR https://github.com/vyos/vyos-1x/pull/1421
=> router-advert: Add deprecate-prefix & decrement-lifetimes

docs/configexamples/zone-policy.rst
Fixing a typo in zone-policy.rst.
=> Fixing a typo in zone-policy.rst.

docs/configuration/service/dhcp-server.rst
Added description about listen-address parameter and corrected syntax
=> dhcp-server: correction in the page

docs/configuration/vpn/openconnect.rst
Fixed gramma mistake in commands
=> openconnect: Fixed gramma mistake in commands

docs/configuration/service/webproxy.rst
Docs update for changes introduced in https://github.com/vyos/vyos-1x/pull/1369
=> T4480: Webproxy: add docs for setting ports to acl Safe_ports and SSL ports

docs/configuration/interfaces/ethernet.rst
```plaintext
gro                  Enable Generic Receive Offload
gso                  Enable Generic Segmentation Offload
lro                  Enable Large Receive Offload
rps                  Enable Receive Packet Steering
sg                   Enable Scatter-Gather
tso                  Enable TCP Segmentation Offloading
```
=> update ethernet hardware offload to reflect current options and order

docs/configuration/service/ssh.rst
```
vyos@vyos:~$ show version
Version:          VyOS 1.4-rolling-202208010217
Release train:    sagitta
vyos@vyos:~$ generate public-key-command 
user                  Username of public key owner
```
=> Update generate public-key-command user subcommand for sagitta

docs/configuration/loadbalancing/index.rst
=> Wan Load Balancing: add warning message - it should not be used with routing protocols

docs/configuration/protocols/mpls.rst, docs/configuration/protocols/ospf.rst
there are some issues regarding ospfv3 configuration and also improve our MPLS description
=> ospfv3 /mpls : wrong commands and description

docs/configuration/policy/route.rst
Gral structure change, moving forward to similar structure that firewall docs. Also, new matching options was added to the docs.
=> Update policy route docs.

docs/quick-start.rst
Current commands look like they were for 1.3?
=> Update Set Firewall

docs/configuration/firewall/general.rst
Corrects assignment of firewall interfaces from older interface assignment to new firewall assignment.
=> firewall: correct rule-set interface assignments

docs/configuration/system/login.rst
Documentation for the authentication by using OTP 2FA.
T874
=> system login: T874: add 2FA support for local and ssh authentication

docs/configuration/policy/route-map.rst
Created documentation for CLI changes in
policy route-map set community
policy route-map set large-community
policy route-map set extcommunity
=> policy: T4660: Created documentation for CLI changes in route-map

docs/configuration/vpn/ipsec.rst, docs/configuration/vpn/site2site_ipsec.rst
Modified the documentation as per the new format/syntax
=> Modified the documentation as per the new format/syntax

docs/configuration/policy/examples.rst
Documentation update for PR: https://github.com/vyos/vyos-1x/pull/1654
=> policy: T2199: Update policy route interface examples

docs/configuration/protocols/isis.rst
Added some examples, and added some more verbosity to IS-IS. There'll likely be more but I figure this is a reasonable addition.
=> Adding configuration examples to IS-IS

docs/configuration/firewall/general.rst
Actions: added jump and return actions. Also jump targets
Matching criteria: dscp and interface matchers.
=> Fwall doc: update actions and matching criterias

docs/configuration/system/login.rst
Documentation for the new feature:
https://phabricator.vyos.net/T4751
=> system login: T4751: 2FA OTP key generator in VyOS CLI

docs/configuration/service/index.rst, docs/configuration/service/ntp.rst, docs/configuration/system/index.rst
* https://github.com/vyos/vyos-1x/pull/1758
* https://github.com/vyos/vyatta-cfg-system/pull/196
* https://github.com/vyos/vyos-build/pull/292
=> ntp: T3008: migrate from ntpd to chrony

docs/configuration/system/host-name.rst
This mainly for search engine optimization -- it took me too much effort to get the correct results I wanted by searching the Internet for `vyos hosts file`
=> add reference to /etc/hosts

docs/configuration/service/ssh.rst, docs/configuration/system/login.rst
https://phabricator.vyos.net/T3506
=> loadkey is to be completely removed from 1.4

docs/configuration/vpn/openconnect.rst
Adds documentation for new functionality added in T4958 - specifically how to configure RADIUS based accounting for OpenConnect.
=> T4958: ocserv: openconnect: document RADIUS accounting

docs/contributing/build-vyos.rst
Separate references mentioning equuleus and state sagitta as current instead
=> Disambiguate sagitta as current

docs/configuration/protocols/failover.rst, docs/configuration/protocols/index.rst, docs/copyright.md
Add documentation for `protocol failover route`
https://phabricator.vyos.net/T1237
https://github.com/vyos/vyos-1x/pull/1358
=> T1237: Add protocol failover route

docs/automation/index.rst, docs/automation/vyos-salt.rst
Add salt configuration examples
=> Salt configuration examples

docs/configuration/highavailability/index.rst
Add virtual-server balancing based on `fwmark` value
=> Add virtual-server fwmark balancing

docs/configuration/protocols/bgp.rst
Added documentation for new BGP roles for RFC 9234
=> Add docs for RFC 9234

docs/configuration/protocols/babel.rst, docs/configuration/protocols/index.rst
Documentation for https://github.com/vyos/vyos-1x/pull/1800.
=> T4977: Add Babel routing protocol

docs/configuration/interfaces/pppoe.rst
Allow user to set pppd holdoff option, meet some ISP's requirement.
* https://vyos.dev/T5098
=> T5098: Update pppoe.rst

docs/configuration/service/ntp.rst
Add `nts` option for NTP server.
Tied to PR vyos/vyos-1x#1913
=> ntp: T5112: NTS support in chrony

docs/installation/cloud/aws.rst
Here is the initial CloudWatch documentation to show a possible way of how to preserve agent configuration between VyOS system image updates, while the VyOS platform-specific scripts feature is under development. Also, this included commit should be cherry-picked to the equuleus branch.
=> AWS: T425: cloudwatch

docs/configuration/system/login.rst
Login limits:
```
set system login max-login-session '3'
set system login timeout '600'
```
=> Add login limits

docs/configuration/protocols/ospf.rst
ospf: Support show detailed ospf routing table.
=> T5123: Update ospf.rst

.gitignore
=> gitignore: add idea idea directory to gitignore

docs/automation/cloud-init.rst
changed the ntp server command format which is now "set service ntp server " and a link reference which are dead or not redirected properly
=> changed the ntp server command format and a link reference

docs/configuration/interfaces/virtual-ethernet.rst
add documentation for interfaces veth , vlans and QinQ features.
=> veth QinQ: add vlans/QinQ documentation

docs/configuration/protocols/isis.rst, docs/configuration/protocols/ospf.rst
Adding documentation for IGP-LDP sync for OSPF and IS-IS.
=> T5081: ISIS and OSPF syncronization with IGP-LDP sync

docs/configuration/system/login.rst
Depends on:
* https://github.com/vyos/vyos-1x/pull/2038
=> T141: add TACACS support

docs/configuration/service/dhcp-relay.rst
Disable commands already merged in vyos-1x: https://github.com/vyos/vyos-1x/pull/2089
=> dhcp-relay: add <disable> command for dhcp and dhcpv6 realys

docs/configuration/nat/nat44.rst
Feature already implemented and merged in vyos-1x: https://github.com/vyos/vyos-1x/pull/2100
=> T4889: NAT Redirection: adding information that dnat redirection is supported

docs/configuration/interfaces/openvpn.rst
add documenation to openvpn DCO ,
=> OpenVPN : add documetation DCO on VyOS

docs/_include/interface-dhcpv6-options.txt
=> interface: T5387: document dhcpv6-pd no-release flag

docs/configuration/service/pppoe-server.rst
when using the "set service pppoe-server client-ip-pool subnet" command, there is no restriction for the subnet mask.
=> pppoe-server: T5418: remove nonexistent restriction

docs/configuration/nat/nat44.rst
Docs for NAT Load balance.
Feature already introduced in https://github.com/vyos/vyos-1x/pull/2119
=> T5014: add NAT Load Balance commands and configuration example.

docs/configuration/firewall/general-legacy.rst, docs/configuration/firewall/general.rst, docs/configuration/firewall/index.rst, docs/configuration/firewall/zone.rst
Update documentation for new firewall structure. Also, keep old/legacy firewall documentation.
Tied to PR https://github.com/vyos/vyos-1x/pull/2016
=> T5160: New firewall cli - Update documentation for new firewall structure

docs/configuration/vrf/index.rst
Added command 'protocols bgp interface <int> mpls forwarding'
=> l3vpn: T5338: Added 'protocols bgp interface <int> mpls forwarding'

docs/configuration/vrf/index.rst
add documentation about label allocation per-next-hop
=> l3vpn : add label allocation mode documentation

docs/configuration/interfaces/macsec.rst
Add documentation related to static MACsec key configuration.
Related to T5447: https://vyos.dev/T5447
=> MACsec: Document static key configuration

docs/configexamples/azure-vpn-bgp.rst, docs/configexamples/azure-vpn-dual-bgp.rst, docs/configuration/firewall/zone.rst, docs/configuration/nat/nat44.rst, docs/configuration/vpn/dmvpn.rst, docs/configuration/vpn/ipsec.rst
correction of ipsec compression syntax  and also added a reference for changes done for zone based firewall
=> correction of ipsec compression syntax 

docs/configexamples/zone-policy.rst, docs/configuration/firewall/general-legacy.rst, docs/configuration/firewall/zone.rst, docs/quick-start.rst
Leave note when needed that new cli is available in latest config, and some examples are explained using legacy configuration
=> Firewall refactor: add visible note in firewall docs:

docs/configuration/firewall/zone.rst, docs/configuration/interfaces/openvpn.rst, docs/introducing/history.rst, docs/quick-start.rst
Fixed some formatting issues on the documentation (as local sphinx compile threw errors for them)
=> Fixed minor issues in documentation

docs/configuration/firewall/general.rst
Add firewall synproxy
Related PR https://github.com/vyos/vyos-1x/pull/2295
=> Add firewal synproxy

docs/configuration/nat/nat44.rst
Add interface-group documentation and Also add firewall rules for allowing destination nat connections.
Tied to PR: https://github.com/vyos/vyos-1x/pull/2355
=> NAT: add interface-group documentation. 

docs/configuration/nat/nat44.rst
Reverts vyos/vyos-documentation#1111
=> Revert "NAT: add interface-group documentation. "

docs/configuration/nat/nat44.rst
Reverts vyos/vyos-documentation#1112
=> Revert "Revert "NAT: add interface-group documentation. ""

docs/configuration/service/mdns.rst
Add mdns repeater docs for additional conf-mode and op-mode options.
PR References:
- vyos/vyos-1x#2009
- vyos/vyos-1x#2307
- vyos/vyos-1x#2447
=> mdns: T5227, T5615, T5719: Update mDNS documentation for additional options

docs/configexamples/ha.rst, docs/configexamples/policy-based-ipsec-and-firewall.rst, docs/configuration/highavailability/index.rst, docs/configuration/nat/nat44.rst, docs/configuration/vpn/l2tp.rst, docs/configuration/vpn/site2site_ipsec.rst, docs/configuration/vrf/index.rst, docs/quick-start.rst
Update some nat commands to new syntax
=> Nat update

docs/_include/interface-dhcp-options.txt
* https://github.com/vyos/vyos-1x/pull/2506
=> dhcp-client: T5760: add CLI option to pass user-class parameter

docs/configuration/interfaces/vxlan.rst
* https://github.com/vyos/vyos-1x/pull/2499
=> vxlan: T5753: add support for VNI filtering

docs/configuration/firewall/global-options.rst, docs/quick-start.rst
See commit message for further details this is for fix to:
code snippet in: https://docs.vyos.io/en/sagitta/quick-start.html
use of English in: https://docs.vyos.io/en/sagitta/configuration/firewall/global-options.html
=> Sagitta_giggum pull request for fix to 1.4.x sagitta documentation

docs/configuration/system/frr.rst, docs/configuration/system/index.rst
* https://github.com/vyos/vyos-1x/pull/2639
=> frr: T4020: document multiple per daemon config knobs

docs/contributing/build-vyos.rst
Changed the position of Native Build to make it easier to distinguish from containers, and updated some content.
=> Native Build update

docs/contributing/build-vyos.rst
Adjusted the Debian version required for container construction and the installation commands for the new version of Docker.
=> Update some outdated entries

docs/configuration/service/lldp.rst
* https://github.com/vyos/vyos-1x/pull/2687
=> snmp: T5855: migrate "set service lldp snmp enable" to "set service lldp snmp"

docs/configuration/system/index.rst, docs/configuration/system/updates.rst
Add an example of online checking for updates
```
set system update-check auto-check
set system update-check url <url>
```
=> Add system update-check example

docs/configuration/container/index.rst
This is a documentation update to reflect changes in [vyso/vyos-1x PR 1955](https://github.com/vyos/vyos-1x/pull/1955).
Please wait for that PR to clear before submitting this one.
=> updating network name to reflect new limitation from 11 to 9

docs/configuration/vpn/openconnect.rst
add new command to enable http security headers on ocserv
=> ocserv: add http-security-headers documentation

docs/configuration/firewall/global-options.rst, docs/configuration/service/dhcp-server.rst, docs/configuration/system/conntrack.rst
Update documentation for commands changed in https://github.com/vyos/vyos-1x/pull/2574
Also update commands for conntrack ignore.
Once PR https://github.com/vyos/vyos-1x/pull/2574 is backported, this PR should also be backported to Sagitta
=> Conntrack timeout

docs/quick-start.rst
I hope this helps someone, it would have helped me.
=> Sagitta: Fix interface command

docs/contributing/build-vyos.rst
Update and adjust some content for easier reading and understanding
=> master Update and adjust 

docs/contributing/build-vyos.rst
Adjusted some content for easier reading
=> Equuleus Adjusted some content for easier reading

docs/configexamples/pppoe-ipv6-basic.rst
Updates PPPoE example syntax for 1.4/1.5 firewall refactor
=> Fix firewall syntax for refactor in PPPoE IPv6 example

docs/contributing/build-vyos.rst
In order to appear easier to read and understand
=> sagitta : Updated some details

docs/configuration/system/updates.rst, docs/installation/update.rst
If we configure "update-check url" we can use `latest` option to update system image.
```
add system image latest
```
=> updates: add system image latest

docs/configexamples/autotest/DHCPRelay_through_GRE/_include/dhcp-server.conf, docs/configuration/service/dhcp-server.rst, docs/installation/install.rst, docs/quick-start.rst
Updates documentation for Kea CLI changes
=> dhcp: T3316: Update documentation for Kea implementation

docs/configuration/pki/index.rst
* https://github.com/vyos/vyos-1x/pull/2758
=> pki: T5886: add support for ACME protocol (LetsEncrypt)

docs/configuration/service/https.rst
Merge after
* https://github.com/vyos/vyos-1x/pull/2773
=> https: add latest CLI changes

docs/quick-start.rst
The firewall changes in1.5 were backported to 1.4.
Should these backtick `` and structure changes also be included? @rebortg
=> Update quick-start from master branch (excluding 1.5 specific DHCP changes)

docs/configuration/service/dhcp-server.rst
Parent PR: https://github.com/vyos/vyos-1x/pull/2817
=> dhcpv6: T3316: Update syntax for DHCPv6 CLI changes to options and range

docs/_ext/vyos.py, docs/automation/cloud-init.rst, docs/automation/command-scripting.rst, docs/automation/vyos-netmiko.rst, docs/cli.rst, docs/contributing/build-vyos.rst, docs/contributing/debugging.rst, docs/contributing/development.rst, docs/contributing/testing.rst, docs/documentation.rst, docs/installation/cloud/aws.rst, docs/quick-start.rst, docs/troubleshooting/index.rst
Hey, 
I stumbled upon some typos and started fixing them. 
Is such a contribution welcome? Should I make smaller commits or do you favor bigger ones?
Best regards,
Sebastian
=> Fix some spell mistakes

docs/configuration/protocols/ospf.rst
Update notice telling users how to exclude passive interface.
=> Update passive-interface default exclusion notice

docs/configuration/service/dns.rst
Add description for new dns forwarding options by task https://vyos.dev/T5687
=> dns forwarding: T5687: Implement ECS settings for PowerDNS recursor

docs/configuration/container/index.rst
Added documentation for task https://vyos.dev/T5955
=> container: T5955: set uid/gid for container

docs/configuration/protocols/bgp.rst
* https://github.com/vyos/vyos-1x/pull/2957
=> bgp: T6024: add additional missing FRR features

docs/configuration/vpn/l2tp.rst, docs/configuration/vpn/sstp.rst
Added PPP options documentation
=> T5971: Added PPP options documentation

docs/configuration/protocols/rpki.rst
* https://github.com/vyos/vyos-1x/pull/2955
=> rpki: T6023: add support for CLI knobs expire-interval and retry-interval

docs/configuration/protocols/static.rst
* https://github.com/vyos/vyos-1x/pull/2980
=> srv6: T5849: add segment support to "protocols static route6"

docs/configuration/system/ip.rst, docs/configuration/system/ipv6.rst, docs/configuration/vrf/index.rst
* https://github.com/vyos/vyos-1x/pull/3016
=> T6001: add option to disable next-hop-tracking resolve-via-default

docs/configuration/system/login.rst
* https://github.com/vyos/vyos-1x/pull/3019
=> login: T5972: add possibility to disable individual local user accounts

docs/contributing/build-vyos.rst, docs/index.rst
=> equuleus: Fix homepage link

docs/contributing/build-vyos.rst, docs/index.rst
Reverts vyos/vyos-documentation#1254
=> Revert "equuleus: Fix homepage link"

docs/configuration/service/pppoe-server.rst
Fully rewritten PPPoE server documentation.
=> Rewritten the PPPoE server documentation

docs/configuration/service/ipoe-server.rst
Fully rewritten IPoE server documentation.
=> Rewritten the IPoE server documentation

docs/configuration/service/ipoe-server.rst, docs/configuration/service/pppoe-server.rst
Fixing IPoE and PPPoE documentation
=> Fixing IPoE and PPPoE documentation

docs/configuration/vpn/pptp.rst
Fully rewritten PPTP server documentation.
=> Rewritten the PPTP server documentation

docs/configuration/vpn/sstp.rst
Fully rewritten SSTP server documentation.
=> Rewritten the SSTP server documentation

docs/quick-start.rst
Update firewall documentation on quickstart file.
=> Quickstart: manual backport to sagitta for firewall configuration in quickstart.

docs/configuration/service/conntrack-sync.rst
=> T6057: Add ability to disable syslog for conntrackd

docs/automation/index.rst, docs/automation/terraform/index.rst, docs/automation/terraform/terraformAWS.rst, docs/automation/terraform/terraformAZ.rst, docs/automation/terraform/terraformvSphere.rst, docs/automation/terraform/terraformvyos.rst
- update AWS + terraform
index
- add Azure + terraform
vSpgere + terraform
=> Update and add information about Terraform

docs/configuration/service/router-advert.rst
* https://vyos.dev/T6118
* https://github.com/vyos/vyos-1x/pull/3125/files
=> radvd: T6118: add nat64prefix support RFC8781

docs/changelog/1.3.rst, docs/changelog/1.4.rst
=> Github: update sagitta branch

docs/changelog/1.3.rst, docs/changelog/1.4.rst, docs/changelog/1.5.rst
=> Github: update current branch

docs/automation/cloud-init.rst
- [x ] I have read the [**CONTRIBUTING**](https://github.com/vyos/vyos-documentation/blob/master/CONTRIBUTING.md) document
=> besides document that vyos_config_commands will do commit and save fixed 80 line len for linter

docs/changelog/1.3.rst
=> Github: update equuleus branch

docs/configuration/container/index.rst
* https://vyos.dev/T6208
* https://github.com/vyos/vyos-1x/pull/3269
=> container: T6208: rename "cap-add" CLI node to "capability"

docs/configuration/firewall/index.rst
=> Firewall: Fix typo "addtion" -> "addition"

docs/configuration/system/ntp.rst
Add this missing section to the docs. This feature was introduced here: https://blog.vyos.io/vyos-project-july-2022-update
* https://vyos.dev/T6201
This should be added to 1.4 and 1.5 too
=> Update docs for `set system ntp interface`

docs/configexamples/policy-based-ipsec-and-firewall.rst
=> Policy-based-ipsec-and-firewall: Fixed typos and capitalisation.

docs/configexamples/ansible.rst
=> Ansible: rephrasing

docs/configuration/interfaces/loopback.rst
=> Fixed minor typo in loopback.rst

docs/configuration/protocols/failover.rst
=> Failover - Slight rephrase of initial summary paragraph.

docs/configuration/service/dns.rst
Made changes to `dns.rst` for the following:
- Fixed spelling mistakes.
- Added information on authoritative domain configuration.
=> Docs: DNS: Added information on authoritative zones
