docs/quick-start.rst

Set up my first VyOS router today and fell into this trap, dhcp-server is now enabled by default when configured and has to be disabled using 'dhcp-server disable' instead.

Remove 'dhcp-server disabled' from quick start

---

README.md
docker/Dockerfile
docs/Makefile

This makes it possible to view the documentation in a web browser as it should be presented.

Add sphinx-autobuild to docker

---

docs/index.rst

fix: add build-vyos in contributing section. That place made the most sense to me.

add build-vyos.rst to toctree

---

docs/services/index.rst

Fix duplicate udp-broadcast-relay reference in service index.
This screenshot shows the duplicate entry in the sidebar.

Remove duplicate udp-broadcast-relay from index

---

docs/qos.rst

"QoS policy inbound is type shaper and is only valid for out" redirected incoming traffic from physical port eth0 to interface ifb0 is represented as outbound traffic from ifb0 interface.
Setup was tested on VyOS 1.2.1

edit traffic policy on ifb interface

---

docs/build-vyos.rst

live-build fails without root and the current docker image automatically
drops to vyos_bld so 'make iso' will fail
https://phabricator.vyos.net/T1521

T1521 Add sudo to the build instructions

---

docs/install.rst

Distinguish different ways of getting the software and clarifying GPG signatures apply only to downloaded LTS images.

Subscribers, non-subscribers and GPG

---

docs/build-vyos.rst

Updated build-vyos.rst to state use of Debian 8 instead of Debian 9 (per CPO on slack)

A tiny PR to fix the ISO build doc Debian Version

---

docs/appendix/examples/index.rst
docs/nat.rst
docs/vpn/wireguard.rst

Initial commit with Tunnelbroker example was missing the navigation link in the index.

Text/spelling fixes, adding additional navigation headers

---

docs/routing/index.rst
docs/services/index.rst

This indexes are short and contain almost no other data.  I think it makes sense to display the table of contents on them, so especially on mobile, they don't feel like such dead ends.

Making these indexes display their TOC

---

docs/quick-start.rst

Lots of rewriting here.  
* Enhancing navigation
* Changing the DNS example to use `listen-address` instead of `listen-on`.  Seems a bit redundant to say something is deprecated, then use it in the example. 
* Making the SSH firewall rules a separate section.  Suggesting that everyone should enable SSH on their WAN by default makes things less secure for the kind of person using this guide.
* Adding a new section for security hardening.  Changing the default vyos user, adding SSH key authentication, forcing key-only SSH logins.

Overhauling and expanding quick start guide

---

docs/services/dns-forwarding.rst

During my testing only the /0 and /32 network prefix lengths worked, specifying a /24 caused the DNS Service to not respond. I have added the /0 network to the above examples so the documentation exists for this required command and will submit a bug report on the issue.

Added allow-from DNS forwarding settings

---

docs/vpn/wireguard.rst

Since this is wontfix due to the mess required, might as well document that a FQDN will break in weird ways.

T1700: Adding note to address this limitation

---

docs/appendix/migrate-from-vyatta.rst

http://vyos.net/so3group_maintainers.key no longer exists and errors with a 404, update to wiki.vyos.net to succesfully be able to continue with doc.

Update so3group_maintainers.key location

---

docs/contributing/documentation.rst

Fix a leftover (and typo) from in the documentation space.

Fix leftover Markdown

---

docs/appendix/examples/azure-vpn-bgp.rst
docs/appendix/examples/azure-vpn-dual-bgp.rst

This PR contains two small fixes for Azure docs.
1) Linked dual VPN guide from the single VPN guide. I've got reports of users missing the latter (maybe when arriving from search engines?), so hopefully this will help.
2) On the dual VPN guide I mentioned that you need an active-passive gateway pair when what you actually need is an active-active gateway pair.

Azure fixes

---

docs/vpn/wireguard.rst

When running the command listed on this page, I receive this error:
run show wireguard named-keypairs pubkey KP01
Invalid command: show wireguard [named-keypairs]
When I instead run the following, the desired output arrives:  run show wireguard keypairs pubkey KP01

Correcting syntax for showing a keypair

---

docs/services/dhcp.rst

Phabricator T1978 for full explanation, dhcp-relay doesn't require specification of more than one interface.

Clarify no need for two interfaces in dhcp-relay configuration

---

docs/appendix/examples/zone-policy.rst

Just a couple of quick fixes for the formatting in the Zone Policy example
I am going to look at sorting this out next:
```
[https://i.imgur.com/Alz1J.png Topology Image]
```

Fixes for formatting in Zone Policy example

---

docs/appendix/examples/zone-policy-diagram.svg
docs/appendix/examples/zone-policy.rst

I have re-drawn the missing diagram on the Zone Policy Example page as an SVG.
I have missed out some of text, because I thought it confused the diagram and the information does appear in the main article text.

Replaced missing diagram on Zone Policy Example with new SVG

---

README.md

The current requirements.txt does not include sphinx-autobuild (it is part of the python3-sphinx on buster)
sphinx-rtd-theme is available as a debian package

update build documentation

---

docs/appendix/vyos-on-baremetal.rst
docs/contributing/build-vyos.rst
docs/contributing/development.rst

some notes where not present in the documentation as "note :" was used instead of "note ::"
s/quiet/quite/g
provided some more information about building on MacOS and/or Windows

various small improvements

---

docs/routing/bgp.rst

Address-family is required to access route-map within neighbor

Added "address-family" to route-map code example

---

docs/vpn/wireguard.rst

It appears the 1.3 documentation erroneously got backported here.  Named keypairs aren't available on crux for wireguard.

wireguard - named keypairs don't exist on crux

---

docs/interfaces/tunnel.rst

IPv6 tunnel endpoints are IP not subnets, addresses are subnets not IPs

tunnel configuration corrections

---

docs/install.rst

PXE documentation was modified and improved,
but at the same time some clarifying details,
which make reading easier, were deleted,
so now those are being restored.

PXE install: restore clarifying details

---

docs/configuration-overview.rst

Add command to show config without private data, restructure seeing &
navigating, and fine-tune other small details.

config-overview: show-config-private and restructure seeing & navigating

---

docs/nptv6.rst

In `VyOS 1.3-rolling-202003071518` the commands are different for the NPTv6 NAT configuration. I've updated them according to the output in my own VyOS router.

NPTv6: Update commands and ip6tables output

---

docs/services/router-advert.rst

The documentation for this never got handled when the section got moved

router-advert: Porting over router-advert documentation

---

CONTRIBUTING.md
docs/contributing/build-vyos.rst
docs/routing/arp.rst

Typo fixed in CONTRIBUTING.md
docs/routing/arp.rst was missing an example because of a missing language tag
docs/contributing/build-vyos.rst troubleshooting diff highlighting wasn't working because the Python lexer didn't understand the code

Docs: Fix typo and code-block errors

---

docs/contributing/build-vyos.rst

The documentation for building VyOS currently recommends adding a non-root user to the docker group. Doing so is equivalent to making that user root and thus should at least carry a warning.
https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

build.rst: Do not recommend using docker group

---

docs/interfaces/bridge.rst

Fix typo, warn STP is not enabled by default, and adjust texts to 72 columns.

bridge: typo, stp warning and indentation

---

docs/firewall.rst

Add link to Zone-Based Firewall KB introduction, edit some
format and adjust texts to 72 characters.

firewall: add link to ZBF intro, some format and indentation

---

docs/appendix/examples/zone-policy.rst

Add contents of the original legend at the wiki's image and adjust
texts to 72 columns.

appendix/examples/zone-policy: add wiki legend and fix indentation

---

docs/services/pppoe-server.rst

Reflect syntax changes from T2314 like RADIUS, name-server or
prefix-delegation; add cfg and op command directives; correct
indentation; and restructure internal order of the page.

pppoe-server: T2314 changes and page restructure

---

docs/configuration-overview.rst

Delete sentence saying the `comment` command only applies to subsections, as that is not correct.
Fix some format mistakes too.

configuration-overview: fix comment command

---

docs/qos.rst

It is only a small urgent fix. The whole section will be replaced soon.

qos: correct how priority values work for shaper.

---

docs/vpn/l2tp.rst

Removed unneeded option "set firewall name OUTSIDE-LOCAL rule 40 destination port '50'" as committing with this rule will throw error + ESP doesnt have a direct destination port number

Fix of sample firewall rules for ESP

---

docs/system/flow-accounting.rst

Hello!
I've noticed small issue in current documentation and fixed it.

Fixed expiry-interval command name to correct one

---

docs/image-mgmt.rst

Explain to keep files into /configure directory
to avoid deletion during upgrades
and slightly reorganize section

Img.managmt/UpdateVyos: keep scripts in /configure and reorganize

---

docs/configuration-overview.rst

Add workaround to allow connection to non trusted hosts.

conf.overview/remote archive: workaround to add remote ssh fingerprint

---

docs/services/mdns-repeater.rst

The address 224.0.0.51 is a Zeroconf address, and not the address associated with mDNS (224.0.0.251) as outlined in the docs. This patch simply changes the zerconf address to be the appropriate mDNS address.
The Multicast address registry I used from IANA can be found here: https://www.iana.org/assignments/multicast-addresses/multicast-addresses.xhtml under `Local Network Control Block`

replace zeroconf address in mDNS repeater doc

---

docs/routing/multicast.rst

Previous merge adding PIM and IGMP did not work properly, command definitions
were not published.

multicast: readd PIM and IGMP.

---

README.md
docs/contributing/build-vyos.rst

Improve the following:
- Differentiate between "crux" and "current" for all commands (git branches and docker image)
- Refactor location of notes to be most appropriate
- State that the switch to buster has already been made
- Upgrade sample command to build 1.2.5 LTS
- Fix above/below in text

Refactor notes. Keep content up to date with Buster and LTS 1.2.5

---

docs/services/console-server.rst

There was a minor typo in the documentation, where the same command was used to list both USB-connected devices and USB serial devices.
This pull updates the second command to the correct value.

Fixed command typo for listing USB serial devices

---

docs/contributing/build-vyos.rst

- To clarify `current` vs `crux` branch and `latest` vs `crux` Docker images
- Fix path issue for build instructions
- Note that if using org image then it is not required to manually pull image beforehand

build-vyos: rewrite documentation

---

docs/qos.rst

Correct typos (etherhet -> ethernet) and add examples of matching on service/protocol in shaper example.

Correct small typos; add matching examples

---

docs/qos.rst

Ingress Shaping is an exceptional case, it should be shown after it is explained how
the standard procedure works.

qos: move ingress shaping to the end of the article

---

docs/qos.rst

Shaper definition does not correspond to HTB cburst but to HTB burst.

qos: fix shaper burst definition

---

docs/qos.rst

Fix an error on the example at 'Applying a traffic policy' and complete the example at 'Shaper' with more matching criteria.

qos: fix and complete examples

---

docs/routing/index.rst
docs/routing/mpls.rst

Basic configuration to act as a P router in an MPLS network.

mpls: basic LDP configuration

---

docs/interfaces/wirelessmodem.rst

AT&T no longer uses the listed APN, and I don't think VyOS documentation should have APN's listed. That would best be up to the end user to find their proper settings for their service provider.

remove outdated and not maintained list of apn

---

docs/system/syslog.rst

This is a simple typo change, I noticed it when reading the documentation for syslog earlier.
It corrects `en` to `an`.
I have also noticed this is in `crux` as well, please let me know if I should raise a 2nd PR fixing it this branch.
Thanks,
dannyt66

docs(syslog.rst): corrected en to an

---

docs/routing/bgp.rst

This was missing an ending ` terminator

bgp: fix missing ` termination

---

docs/install.rst

Add sync to dd command as suggested by John, fix a little typo
and restore PXE index hierarchy levels (which got lost with last changes).

installation: add dd parameter for usb creation

---

docs/vpn/anyconnect.rst
docs/vpn/index.rst

This documentation describes how to configure AnyConnect-Server on VyOS

T2810: Docs for vpn anyconnect-server

---

docs/interfaces/vxlan.rst

Replaced "link" with "source-interface" and "remote-port" with "port"
vyos@vyos# set int vxlan vxlan1
+  address      IP address
description  Interface specific description
disable      Administratively disable interface
> firewall     Firewall options
group        Multicast group address for VXLAN interface
> ip           IPv4 routing parameters
> ipv6         IPv6 routing parameters
mac          Media Access Control (MAC) address
mtu          Maximum Transmission Unit (MTU)
> policy       Policy route options
port         Destination port of VXLAN tunnel (default: 8472)
remote       Remote address of VXLAN tunnel
source-address
VXLAN source address
source-interface
Physical interface used for connection
vni          Virtual Network Identifier

vxlan syntax correction: link and remote-port parameters are not available in rolling release

---

docs/routing/mpls.rst

Moved the configuration mode commands and descriptions to fit VyOS template. I wrote them wrong previously.

MPLS: fix conf-mode definitions and line breaks

---

docs/configuration-overview.rst
docs/system/user-management.rst

A standard `scp` call implies a ":" between the remote host
and the remote path. Let's reflect it in the doc to avoid
any confusion.

Correct the scp URI

---

docs/services/conntrack.rst

Make it clear that it's possible to use the "peer" statement after the interface command, to enable UDP mode instead of Multicast mode.

Update conntrack.rst to document Unicast sync

---

docs/routing/mpls.rst

In this commit, we added the previous MPLS configurations that were added as
well as the new local label allocation documentation. I went back and made sure
that I was able to grab the rest of what was missing in the documentation and 
added it.

mpls-conf: T915: Added documentation for MPLS for missing features

---

docs/debugging.rst

While debugging an issue I found that the debugging document is lacking a section about debugging python code on the live system so I decided to try pdb and document my approach in doing so.

debugging: add section about using pdb

---

docs/configuration/system/flow-accounting.rst

This PR modifies the documentation for the flow-accounting egress feature (see https://github.com/vyos/vyos-1x/pull/647)

flow-accounting: T3132: enable egress traffic accounting

---

docs/configuration/highavailability/index.rst

Docs » Configuration Guide » High availability >> VRRP acronym has been
corrected to Virtual Router Redundancy Protocol

VRRP acronym is corrected

---

docs/configuration/protocols/mpls.rst

Added the ordered control command in the documentation.
Also added the RFC in which it is referred to as well.

mpls: T915: Added documentation for LDP ordered control

---

docs/configuration/interfaces/openvpn.rst

- use `/config/auth/openvpn` consistently when using and creating server certificates 
- currently, it's `/config/auth/ovpn` in one place and `/config/auth/openvpn` in the other for server doc

doc: consistent openvpn folder naming

---

docs/configuration/protocols/isis.rst

Due to [T3210](https://phabricator.vyos.net/T3210)

isis: change the command

---

docs/configuration/protocols/bgp.rst

This is a documentation addition for the allow range command
within BGP, as well as the associated limit command as well.
There was a few spelling mistakes that were fixed too, but
not anything big.

bgp: T1875: Add BGP allow range command documentation

---

docs/configuration/protocols/ospf.rst

ospf: change redistribution metric value

---

docs/configuration/protocols/bgp.rst

Fix redistribute bgp parameters.
It doesn't make sense to "redistribute" bgp over bgp.
redistribute should use only other protocols, than bgp.

bgp: Fix redistribute parameters

---

docs/configuration/protocols/bgp.rst

Adding documentation on the default RFC8212 behavior for FRR, and
how in VyOS we are changing that default. Also added information
on the toggle option to enable/disable said RFC8212 functionality.
The PR for the work is https://github.com/vyos/vyos-1x/pull/744

BGP: T2100: Adding RFC8212 option toggle.

---

docs/configuration/vpn/l2tp.rst

dns-servers parameter is replaced with name-server in the latest release
Old Syntax:
set vpn l2tp remote-access dns-servers server-1 '198.51.100.8'
set vpn l2tp remote-access dns-servers server-2 '198.51.100.4'
New Syntax:
set vpn l2tp remote-access name-server '198.51.100.8'
set vpn l2tp remote-access name-server '198.51.100.4'

Correction in command syntax "set vpn l2tp remote-access dns-servers"

---

docs/configuration/nat/nat66.rst

The latest implementation modifies the configuration syntax of nat66 to fully support nat66 address translation (not prefix translation)

nat66: T2518: Modify configuration command use case

---

docs/troubleshooting/index.rst

The ordering of boot steps is corrected in Troubleshooting/System Information/Boot Steps section. I have renumbered the last to number from 10, 11 to 9, 10.

The last two numbers 10, 11 in Boot Steps are corrected 

---

docs/installation/image.rst

s/bootet/booted/ in Image Instalation docs

---

docs/configuration/system/ip.rst
docs/installation/cloud/cloud-init.rst
docs/installation/cloud/index.rst

- code-blocks were not displaying in two files
- lowered TOC depth in docs/installation/cloud/index.rst

Fix code-blocks not displaying

---

docs/configuration/protocols/bgp.rst

BGP as number is no longer represented as a tag node on "protocols bgp <asn>" but rather is not represented as leafNode under "protocols bgp local-as <asn>"
Must be merged together with https://github.com/vyos/vyos-1x/pull/793

bgp: adjust to new CLI format

---

docs/configuration/firewall/index.rst

Fix a few typos I spotted in the firewall docs.

Fix typos in configuration/firewall

---

docs/configuration/interfaces/wireguard.rst

corrects some grammar mistakes and reads better

Style changes to wireguard documentation

---

docs/configuration/interfaces/tunnel.rst

VyOS 1.3 version: added the command configuration for gretap and corrected the syntax in
dhcp-relay example

T3458-e::tunnel interface:added GRETAP section for 1.3 ver

---

docs/configuration/system/name-server.rst

As this thread states:
https://forum.vyos.io/t/system-name-server-vrf-aware/6710
There is no way to force system DNS traffic via a specific VRF, which is a pretty common scenario.
For example one could expect that all system services like DNS, auth, syslog, NTP, etc would use the management VRF (as specified by the user).

Add information about specific VRF routing

---

docs/_include/interface-address-with-dhcp.txt

`dhcp` and `dhcpv6` were missing the `address` part of the line, and the command does not work.
Tested in 1.3.0 rc1

Fix DHCP address syntax

---

docs/configuration/interfaces/wireguard.rst

There was a type in the IPv6 address of the iPhone peer in the example.

Wireguard: Fix IPv6 in iPhone peer example

---

docs/configuration/service/console-server.rst

Corrected the syntax for the operational command
from "connect console-server <device>" to "connect console <device>"

service/console-server:correction of operational command 'connect'

---

docs/configuration/service/console-server.rst

Corrected the syntax for the operational command
from "connect console-server " to "connect console "

equuleus/console-server:correction of operational command 'connect'

---

docs/configuration/protocols/rpki.rst

I took the remark that rpki.readthedocs.io is somewhat NLnet Labs’ tools-centric to heart and made it completely neutral. It no longer has any vendor-specific documentation at all.

Make rpki.readthedocs.io neutral

---

docs/troubleshooting/index.rst

Here we're just making a small change to reflect
that we added do not fragment to ping.
Main PR is https://github.com/vyos/vyos-1x/pull/885

PING: T3634: Adding do not fragment to Ping

---

docs/configuration/service/dhcp-server.rst

The secondary server in the DHCP failover example was set to primary. I assume this should be 'secondary' instead?
Edit: Should probably also be pushed/cherry picked in `equuleus` branch?

Changed typo in DHCP Failover

---

docs/introducing/about.rst

It's means "it is". Possessive its has no apostrophe.

Grammar fix in About

---

docs/configuration/protocols/bgp.rst

Since 1.3 , prefixes used in BGP `network` statements don't need to exist in your routing table by default, but the examples at the bottom of the page hadn't been updated for this change.

Rewrite eBGP example comments

---

CONTRIBUTING.md

The link in the contribution guide is now a 404. I believe this URL is what it's meant to point to.

Update link to the documentation

---

docs/configuration/system/login.rst

While adding `&quot;` support in T971, I noticed that `options` weren't
documented at all. This commit adds documentation for ssh options,
including the use of `&quot;`

T971 Document the use of ssh key options

---

docs/configuration/interfaces/wireguard.rst

Corrected a mistake where it showed the wrong subnet in the description for the applied rule under local side annotated commands.

Update wireguard.rst to correct typo

---

docs/configuration/protocols/mpls.rst

Here we are adding documentation showing the separation of MPLS enable
for interfaces separately from LDP. This was decoupled a while ago
but I completely forgot to add it to the documentation.
It is added now though.

Adding MPLS documentation changes that I forgot to add a long time ago.

---

docs/configuration/interfaces/wireguard.rst

This appears to be an error in the documentation. Tested it with vyos 1.3-rc6

changed to use 'static interface-route' instead of 'static route'

---

docs/configuration/vpn/ipsec.rst

A private key is also needed to finish the ipsec setup which is not mentioned
in the section "Source tunnel from loopbacks/Setting up IPSec". I have added
for reference.

VPN IPsec: Added a note related to rsa key

---

docs/installation/update.rst

Updated the example to include the new iso location on Amazon S3. Also updated the hint for the page where the list of nightly builds are located.

Updated rolling release location and example

---

docs/configuration/protocols/bfd.rst

Per https://phabricator.vyos.net/T3267, per-interface configuration for OSPF has been moved from the 'interface' to the 'protocols' tree. Finally, for op-mode, per https://phabricator.vyos.net/T4077, 'show protocols bfd' has been renamed to 'show bfd'.

BFD: fix commands for operational mode and configuration mode

---

docs/configuration/vpn/ipsec.rst

In latest rolling release, the parameters local-ip and remote-ip are replaced with source-address and remote. These are still present in the documentation, replaced with correct values.
vyos@vyos# set int tunnel tun0
remote       Tunnel remote address
source-address
Source IP address used to initiate connection

vpn-gre:incorrect syntax: local-ip and remote-ip changed to source-address and remote

---

docs/_include/interface-eapol.txt

This PR updates the eapol documentation to account for the PKI changes introduced in VyOS 1.4. It also documents the parent CA behavior I've proposed at https://github.com/vyos/vyos-1x/pull/1227 (not yet merged).

T4245: interface-eapol: Update for VyOS 1.4 PKI changes and parent CA behavior

---

docs/configuration/interfaces/wireguard.rst

Some minor fixes, improvements and extensions on the WireGuard (Interfaces) page. Everything was tested against the Vyos version 1.4-rolling-g7c82c5c7104-20220217. This version should be nearly identical to the rolling release 1.4-rolling-202202150317. 
- Fixing not working named private key command. The current command throws the following error.
```
Key is not valid 44-character (32-bytes) base64
Value validation failed
Set failed
```
- Updating the public key in the example to match the private key as generated in the previous section.
- Explaining the persistent-keepalive flag in the RoadWarrior section
- Renaming wg0 to wg01 to make the interface name consistent with the rest of the document and between the command and the related output.
I am submitting these changes as end-user of …

WireGuard (Interfaces) improvements and fixes

---

docs/configuration/vpn/ipsec.rst

https://phabricator.vyos.net/T1856
https://github.com/vyos/vyos-1x/pull/1230
Starting from 02.22.2022 in version 1.4 it will be possible to select the following commands:
`  life-bytes ESP life-in-bytes`
`  life-packets ESP life in packets`
Please add changes to the documentation for version 1.4

Ability to set SA life bytes and packets

---

docs/installation/install.rst

512 MB is not enough for the full minimum operation of VYOS.
When adding a 466 MB image, it fails to boot into RAM and throws an "out of memory" error. Please change the minimum value of RAM from 512 to 1024.

Hardware requirements RAM 1024

---

docs/quick-start.rst

The syntax changed from integer to one of `second`, `minute`, `hour`.

quick-start: firewall has a new recent time syntax

---

docs/configuration/protocols/bgp.rst

Add docuemntation for:
``
vyos@vyos# set protocols bgp 65540 neighbor 192.0.2.2 
...
solo   --->   Do not send back prefixes learned from the neighbor
...
``

BGP: add documentation for <solo> option in neighbor configuration

---

docs/configuration/vpn/openconnect.rst

The last version of the documentation was outdated and did not allow to raise ocserv. 
Update reflects current commands + new functionality of OTP

OpenConnect new new syntax + OTP 2FA

---

docs/configuration/vpn/openconnect.rst

Information about command added:
`show openconnect-server user <username> otp <full | key-b32 | key-hex | qrcode | uri >`
[https://phabricator.vyos.net/T4420](https://phabricator.vyos.net/T4420)

ocserv. Added show user OTP key

---

docs/configuration/firewall/index.rst

Documentation for "firewall connection-status nat" feature.
cli new option:
```
vyos@vyos# set firewall name FOO rule 1 connection-status nat 
destination  Match connections that are subject to destination NAT
source       Match connections that are subject to source NAT
vyos@vyos# set firewall ipv6-name FOO rule 1 connection-status nat 
destination  Match connections that are subject to destination NAT
source       Match connections that are subject to source NAT
```

Add firewall connection-status nat documentation

---

docs/contributing/build-vyos.rst

Fixed typo in VMware section. 
Added comment it requires ovftool already installed.

Fix typo in VMware section

---

docs/configuration/policy/route-map.rst

Update documentation for new feature request T4449, which adds more options to route-policy match ip nexthop

Route-map - Extend options for ip next-hop match

---

docs/configexamples/ha.rst

In version vyos 1.4 rolling 202205 you define the virtual-address in the vrrp group with just address

Rename virtual-address option in address

---

docs/configuration/vpn/sstp.rst

Added information on how to change the SSTP server port according to:
[sstp: T4444. Port number changing support](https://phabricator.vyos.net/T4444)

sstp: T4444. Port number changing support

---

docs/configexamples/l3vpn-hub-and-spoke.rst
docs/configuration/interfaces/openvpn.rst
docs/configuration/vrf/index.rst
docs/contributing/build-vyos.rst

Modified the grammatical  errors and bgp syntax which is modified in the
latest rolling version
`set protocols bgp parameters default no-ipv4-unicast` doesn't exist and the setting is set by default now

syntax and grammar check

---

docs/configuration/firewall/index.rst

I have added the inverse-match option in the configuration section of the firewall matching criteria.
This would be my first-ever pull request and contribution to anything, so please bear with me.

Firewall: T4299: Add inverse-match to geoip

---

docs/configuration/interfaces/bridge.rst

... and update the description for `igmp querier`
to match the fact that MLD querier is also controlled by that option.

bridge: Add IGMP/MLD snooping

---

docs/configuration/firewall/index.rst

Added recent matching criteria to the documentation.
Currently this information is only present in the "Quick start" section.

Firewall: add 'recent' matching criteria

---

docs/configuration/policy/route-map.rst

Information about commands added:
set policy route-map <text> rule <1-65535> match ipv address
prefix-len <0-32>
set policy route-map <text> rule <1-65535> match ipv6 address
prefix-len <0-128>

route-map match prefix-len command

---

docs/configuration/pki/index.rst

Fixed typo in command to match VyOS CLI:
```
$ show pki
<Enter>       Execute the current command
ca            Show x509 CA certificates
certificate   Show x509 certificates
crl           Show x509 certificate revocation lists
```

Fix typo in command: "certificate" instead of "certificates"

---

docs/configuration/highavailability/index.rst

Using the same VRID on the same interface is allowed when they
are different address families.

T4665: Keepalived: Docs for using the same VRID

---

docs/configuration/service/console-server.rst

Documentation changes for vyos/vyos-1x#1559

conserver: T4717: Support for setting a name for console-server devices

---

docs/configuration/vpn/site2site_ipsec.rst

Migration and Change boolean nodes "enable/disable" to
disable-xxxx, enable-xxxx and just xxx for VPN IPsec
configurations
- IKE changes:
- replace 'ipsec ike-group <tag> mobike disable'
=> 'ipsec ike-group <tag> disable-mobike'
- replace 'ipsec ike-group <tag> ikev2-reauth yes|no'
=> 'ipsec ike-group <tag> ikev2-reauth'
- ESP changes:
- replace 'ipsec esp-group <tag> compression enable'
=> 'ipsec esp-group <tag> compression'
- PEER changes:
- replace: 'peer <tag> id xxx'
=> 'peer <tag> local-id xxx'
- replace: 'peer <tag> force-encapsulation enable'
=> 'peer <tag> force-udp-encapsulation'
- add option: 'peer <tag> remote-address x.x.x.x'
If peer name is IPv4 or IPv6 address add remote-address via
migration script

ipsec: T4118: Change IPSec syntax

---

docs/_include/interface-common-without-dhcp1.txt
docs/_include/interface-common-without-mac.txt
docs/configuration/interfaces/tunnel.rst

Mac address option is not present for tunnel interface so had to remove from the documentation. As the include pages are called, added two new files to reflect the changes

tunnel-mac: mac addr option unavailable for tunnel interface

---

docs/configuration/policy/examples.rst

Adding a complete example on out to apply the Policy Route config directive to adjust MSS, given the require co-configuration directives 'protocol tcp' and 'tcp flags SYN', which are missing from the brief description of the mss adjust feature in the policy route page.

Add MSS clamp example

---

docs/contributing/build-vyos.rst

The documentation under https://docs.vyos.io/en/latest/contributing/build-vyos.html (latest rolling release) is outdated. The `./configure` step does not work anymore, no `configure` file found.
This pull request updates the documentation with steps that have been tested against the version `1.4-rolling-g3871fb67ec1-20221105` and uses the build-vyos-image python script directly if the build process needs to be customized.

Updating the documentation to reflect the new build process

---

docs/configuration/firewall/general.rst

This pull request adds the accompanying documentation for the `address-mask` field added in: https://github.com/vyos/vyos-1x/pull/1641
Relevant Phabricator task for discussion: https://phabricator.vyos.net/T4612

firewall: T4612: Support arbitrary netmasks Documentation

---

docs/configuration/firewall/index.rst

This PR updates the documentation regarding the TCP MSS clamping value changes and options described in https://github.com/vyos/vyos-1x/pull/1557, merge after the preceding PR is merged.

firewall: T4709: update documentation for TCP MSS clamping

---

docs/configuration/firewall/general.rst
docs/configuration/policy/route.rst

Phabricator task for such new feature: https://phabricator.vyos.net/T4886
PR already merged in vyos-1x: https://github.com/vyos/vyos-1x/pull/1718

T4886: Add connection-mark information to firewall and policy docs.

---

docs/configuration/vpn/site2site_ipsec.rst

There was a typo in the reference for the image added in the previous commit, corrected that.

close-action: added an image to the details.

---

docs/configuration/interfaces/wireless.rst

Added line in the "Wireless options (Station/Client)" section to better match the output in "Resulting in" section.

Added line in the example to match "Resulting in"

---

docs/configuration/vpn/ipsec.rst

Added Pseudo-Random Functions (PRF) information
in IPSEC documentation.

ipsec: T4925: Added PRF information in IPSEC documentation

---

docs/configuration/trafficpolicy/index.rst

This is the documentation update for [https://github.com/vyos/vyatta-cfg-qos/pull/17](https://github.com/vyos/vyatta-cfg-qos/pull/17) to indicate that the default leaf qdisc is now `fq-codel` as opposed to `fair-queue`.

traffic-policy: T2721: Update docs to indicate fq-codel is the default leaf queuing discipline for shaper/HTB

---

docs/configuration/nat/nat66.rst

There were two different missing spaces between words. Simple PR to add two spaces to resolve the issue.

Fix two typos in nat66.rst

---

docs/configuration/service/dns.rst

Support optional custom port for name-server forwarders.
Tied to vyos/vyos-1x#1914

dns: T5113: Support custom port for name-server forwarders

---

docs/configuration/protocols/failover.rst

Add protocol failover route policy.
```
set protocols failover route 192.0.2.55/32 next-hop 192.168.122.1 check policy 'any-available'
set protocols failover route 192.0.2.55/32 next-hop 192.168.122.1 check target '192.168.122.25'
set protocols failover route 192.0.2.55/32 next-hop 192.168.122.1 check target '192.168.122.1'
```
merged in https://github.com/vyos/vyos-1x/pull/1966

Add protocol failover route policy

---

docs/configuration/service/dns.rst

In sagitta, the suggested option for domain forwarding is name-server.
(I assume that the master branch is also the branch used for sagitta. is that correct?)

fix: correction of domain forwarder configuration name-server instead of server in sagitta

---

docs/configuration/policy/route-map.rst

Add policy route-map match protocol
```
vyos@r14# set policy route-map foo rule 10 match protocol 
babel                Babel routing protocol (Babel)
bgp                  Border Gateway Protocol (BGP)
connected            Connected routes (directly attached subnet or host)
isis                 Intermediate System to Intermediate System (IS-IS)
kernel               Kernel routes
ospf                 Open Shortest Path First (OSPFv2)
ospfv3               Open Shortest Path First (IPv6) (OSPFv3)
rip                  Routing Information Protocol (RIP)
ripng                Routing Information Protocol next-generation (IPv6) (RIPng)
static               Statically configured routes
table                Non-main Kernel Routing Table
vnc                  Virtual Network …
```

Add policy route-map match source protocol

---

docs/configuration/vpn/openconnect.rst

This PR adds documentation related to [T3896](https://vyos.dev/T3896) which was merged [here](https://github.com/vyos/vyos-1x/pull/1783) on configuring the OpenConnect server VPN to allow for user/group specific configuration files.

T3896: ocserv: openconnect: document identity based configuration

---

docs/automation/cloud-init.rst

the reference link https://yamlvalidator.com/ mentioned in cloud-init page is no more available so replaced it with new https://www.yamllint.com/

link https://yamlvalidator.com/ is dead

---

docs/configuration/vpn/openconnect.rst

My original PR mistakenly had the warning text indented incorectly which caused some of the text to flow out of the warning box and appear as regular text below.
This PR addresses that issue

Fix warning formatting on OpenConnect VPN configuration page

---

.github/workflows/pr-conflicts.yml

git Actions use ubuntu-22.04 instead of deprecated ubuntu-18.04 for PR conflicts checker
actions/runner-images#6002
https://vyos.dev/T5258

T5258: git Actions use ubuntu-22.04 for PR conflicts checker

---

docs/configuration/interfaces/pppoe.rst

On IPv6 via PPPoE the MSS should be 1432 instead of 1452 as the v6 header is 60 bytes.

MSS-Clamp IPv6 via PPPoE

---

docs/_include/interface-mirror.txt
docs/configuration/interfaces/ethernet.rst

two paragraphs are defined about the mirror option, removed the paragraph having the older cli structure.

interface mirror options are changed.

---

docs/configuration/interfaces/l2tpv3.rst

The previous RFC pointed to the XMPP (Instant Messaging Standard) specification.

L2TPv3: Fix typo

---

docs/installation/virtual/docker.rst

* Adding curl to download current rolling version from github
* Replacing old 2021 file with the current 2023 version

Updating documentation

---

docs/configuration/protocols/index.rst
docs/configuration/protocols/pim6.rst

https://github.com/vyos/vyos-1x/pull/2179 added basic MLD support for IPv6 multicast. Adding documentation accordingly.

T5518: Document `protocols pim6`

---

docs/configuration/interfaces/openvpn.rst

Since pre-shared keys are deprecated, we need to document the migration path.

openvpn: Add peer fingerprint mode

---

docs/configuration/firewall/general-legacy.rst
docs/quick-start.rst

I've written a new `nftables`-oriented firewall quick start guide, which aims to provide enough context for the reader to reason about the new firewall backend. I did *a lot* of testing with different variations on a fresh qotom box that was attached to my existing network on the WAN side and my laptop on the LAN side; this is the variant that touches on all the most important concepts while meeting the needs of a basic NAT gateway configuration.
The original sources for the base of my configuration were the [current nftables firewall examples](https://docs.vyos.io/en/latest/configuration/firewall/general.html#operation-mode-firewall) and the examples in netfilter configuration. The new nftables firewall could definitely use significantly more documentation, but I'll keep my PRs atomic. …

quick-start: update firewall tutorials to reflect nftables-based firewall commands

---

docs/troubleshooting/index.rst

Fix typo, 'ehternet' -> 'ethernet'

---

docs/configuration/interfaces/wireguard.rst

Noticed a few typos in the Wireguard documentation. Here's a fix.

Fix two typos in Wireguard doc

---

docs/configexamples/index.rst
docs/configexamples/site-2-site-cisco.rst
docs/configuration/vpn/ipsec.rst
docs/configuration/vpn/site2site_ipsec.rst

Added config example of vpn ipsec site-to-site with cisco device using flexvpn

Added config example of vpn ipsec site-to-site

---

docs/configuration/interfaces/vxlan.rst

Needs to be merged after https://github.com/vyos/vyos-1x/pull/2413

vxlan: T5668: add CLI knob to enable ARP/ND suppression

---

.github/workflows/update-translations.yml
requirements.txt

Looks like lxml build stopped to work because actions/setup-python started to install Python of version 3.12 which has some changes regarding ob_digit usage
https://github.com/cython/cython/issues/5238
Temporary solution is to use Python 3.11.x. Also reverted unnecessary lxml downgrade in requirements.txt

Fixed lxml build (Python 3.12 issue)

---

docs/cli.rst

Corrected spelling and changed the way the 'set' command was being displayed.

Small document changes.

---

docs/automation/command-scripting.rst

In case of using current example for sourcing commands from non-shell scripts, I have faced with issue like next:
```shell
/home/vyos/update-network-groups-wrapper.sh: line 14: source: filename argument required
source: usage: source filename [arguments]
```
We have to use [process substitution](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html) here instead of input redirection.

Update script ex with the correct "source" syntax

---

docs/configuration/service/mdns.rst

Browsing the v1.5.x docs, I noticed in the Services configuration guide [the example](https://docs.vyos.io/en/latest/configuration/service/mdns.html#example) for mDNS not being correctly formatted to be subsection of mDNS Repeater in the navigation tree. It appears #1147 introduced that change.

Fix mDNS documentation to correct Example issue

---

docs/automation/vyos-api.rst

HTTP API add `reboot` and `poweroff` endpoints examples
https://vyos.dev/T5767

HTTP API add reboot and poweroff endpoints example

---

docs/configuration/protocols/isis.rst

Adding basic descriptions of ISIS fast reroute documentation. It's sparse because FRR didn't really document it very deeply. But we'll get more as time goes on. This is part of https://vyos.dev/T5530

Add ISIS fast reroute documentation

---

docs/configuration/vpn/sstp.rst

Fixed 'client-ip-pool' configuration in the example

sstp: T5688: Fixed 'client-ip-pool' configuration in the example

---

docs/configuration/nat/index.rst
docs/configuration/nat/nat64.rst

Add a simple description and example of NAT64
https://vyos.dev/T160
https://github.com/vyos/vyos-1x/pull/2578

NAT64: Add example of configuration for NAT64

---

docs/automation/index.rst
docs/automation/vyos-pyvyos.rst

added ref to pyvyos python sdk

pyvyos python sdk 

---

docs/automation/cloud-init.rst

Added 'vyos-install' module documentation in cloud-init

cloud-init: Added 'vyos-install' module documentation

---

docs/configuration/firewall/global-options.rst
docs/configuration/service/dhcp-server.rst

Update docs for fix applied in https://github.com/vyos/vyos-1x/pull/2551
This PR should also be backported to Sagitta docs.

dhcp-server: update docs for op-mode command <show dhcp server leases>

---

docs/contributing/build-vyos.rst

Changed data/defaults.json to data/defaults.toml, as defaults.json is no longer used
Also updated the alias to reference 'sagitta' instead of 'crux'

Sagitta: Updated build documentation

---

docs/configuration/service/monitoring.rst

While setting up Monitoring for my vyos deployment, I noticed that the example mentioned in docs are not accurate. 
I was able to get it working anyway by using tab completion. 
So here is the updated docs for Influxdb

Update Monitoring Docs for Influxdb

---

docs/configuration/service/ipoe-server.rst
docs/configuration/service/pppoe-server.rst
docs/configuration/vpn/sstp.rst

Changed IPv6 pool documentation in accel-ppp services to named IPv6 pools.
https://vyos.dev/T5865

Changed IPv6 pool documentation in accel-ppp services

---

docs/configuration/container/index.rst

very little fix, a "set" was forgotten in the container documentation

fix a forgotten "set"

---

docs/configuration/trafficpolicy/index.rst

In order to set up ingress shaping using the example, you also need to create the ifb0 interface.  
Otherwise by following just the commands given you will receive a "Requested redirect interface "ifb0" does not exist!" error.  
At least to me it was not clear if these commands also created the IFB interface.

Add additional step to ingress shaping

---

docs/quick-start.rst

New to VyOS (thus reading the quick start guide) so if this is not how it's supposed to work I apologize, but in order for the DHCP scope to work properly as laid out in the quick start guide I had to set the shared-network-name to the same as the interface description. I figured updating the interface description in the guide would be easier than modifying the scopes, and would help others getting started.

Quick Start - Set interface description to match DHCP scope

---

docs/configuration/service/dns.rst

Rewrote entire Dynamic DNS portion of ../configuration/service/dns.html to align with T5791 "Update dynamic dns configuration path to be consistent with other areas of VyOS"

Rewrote Dynamic DNS documentation/examples to align with T5791

---

docs/configuration/highavailability/index.rst

A new path was added to the sync-group config tree

T6020:vrrp health-check script not applied correctly in keepalived.conf

---

docs/configuration/firewall/ipv4.rst

Updated "configuration/firewall/ipv4.html" to include rules introduced by https://vyos.dev/T5614

Added conntrack-helper rules from T5614 to ipv4 rules documentation

---

docs/configuration/policy/route-map.rst

Add documentation about new route-map set option
* https://vyos.dev/T6129
* https://github.com/vyos/vyos-1x/pull/3139
`sagitta`

policy: T6129: add route-map option "as-path exclude all"

---

docs/changelog/1.3.rst

Github: update equuleus branch

---

docs/automation/vyos-api.rst

Add missing example of operation 'exists' for retrieve endpoint.
* https://vyos.dev/T6135

http-api: T6135: add details on op 'exists' for retrieve endpoint

---

docs/configuration/interfaces/bridge.rst

Linux bridge uses EtherType 0x8100 by default. In some scenarios, an EtherType value of 0x88A8 is required.
Reusing CLI command from VIF-S (QinQ) interfaces:
set interfaces bridge br0 protocol 802.1ad
* https://vyos.dev/T6125
* https://github.com/vyos/vyos-1x/pull/3158

bridge: T6125: support 802.1ad (ethertype 0x88a8) VLAN filtering

---

docs/configuration/service/dhcp-server.rst

Added configuration introduced in T4389 dhcp: add vendor option support for Ubiquity Unifi controller to VyOS 1.5.x documentation
* https://vyos.dev/T4389

T4389: extend DHCP server documentation on vendor options

---

docs/changelog/1.3.rst
docs/changelog/1.4.rst

Github: update sagitta branch

---

docs/configuration/interfaces/openvpn.rst

openvpn option: "--client-cert-not-required" is not accepted and openvpn service goes down, need to replace with new value "--verify-client-cert none" in the define example
* https://vyos.dev/Txxxx
backported to Sagitta

openvpn option: "--client-cert-not-required" is not accepted

---

docs/configuration/protocols/rpki.rst

HTTP is not used for RPKI information, the RTR protocol is used, which works on top of plain TCP. Although some implementations can use TLS, VyOS (and FRR) do not support it, and use either plain TCP or SSH.
This Pull Request corrects the docs to reflect that.
FRR and VyOS never supported TLS and HTTP, so this should be backportable to 1.3 / 1.4 too.

Fix mistake in RPKI documentation about the use of TLS

---

docs/configuration/service/conntrack-sync.rst

one option was added:
```
set service conntrack-sync startup-resync
```
* https://vyos.dev/T1244
1.5:
https://github.com/vyos/vyos-1x/pull/3254
1.3:
https://github.com/vyos/vyos-1x/pull/3256
This should be backported to 1.4 and 1.3 too

conntrack-sync: T1244: Support for StartupResync in conntrackd

---

docs/configuration/protocols/rpki.rst

- Rephrase introduction slightly
- Replace GoRTR w/ StayRTR (official CF deprecation and assignment of succesor)
- Add rpki-client (probably the best software to use with StayRTR)
- Remove RIPE RPKI Validator (deprecated)
- Replace RIPE's instructions (deprecated) with NLnet Labs'
- Update ROA coverage metrics (yay for 20% -> 60% ROA coverage!)
- Add missing Oxford comma
- Replace RIPE's deprecated test with Cloudflare's
The changes should be backportable to 1.3 and 1.4

Refresh RPKI Document

---

docs/configuration/loadbalancing/reverse-proxy.rst

Made changes to `reverse-proxy.rst` for the following:
- Fixed spelling mistakes.
- Added information on using SSL for backend connections.

Docs: Reverse-Proxy: Added info on backend ssl and fixed spelling mistakes
